# Generated by Django 2.2.7 on 2019-11-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
